---
format_version: "10"
pipeline:
  name: "Example Pipeline"
  group: "My Pipelines"

  materials:
    - git: "https://github.com/example/repo.git"

  stages:
    - name: "Build"
      jobs:
        - name: "Execute Command"
          tasks:
            - exec:
                command: echo "Hello, World!"


