# Pipeline for Gradle Java Application Build
---
pipelines:
  - name: gradle-java-build
    group: my-pipelines
    materials:
      - git: "https://github.com/Jewel73/naztech-jdbc.git"
    stages:
      - name: build
        jobs:
          - name: gradle-build
            tasks:
              - exec: "./gradlew build"

